name: Python CI

on:
    push:
        branches: [ main ]

jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'

            - name: Install pytest
              run: pip install requests pytest

            - name: Run tests
              run: pytest test_script.py

            - name: Run unit tests
              run: pytest unit_tests.py

            - name: Run site pinger script
              run: python site_pinger.py

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: health-check-result
                path: status.json
                if-no-files-found: error

            - name: Check content of status.json
              run: |
                STATUS=$(jq -r '.status' status.json)
                echo "Status from JSON: $STATUS"
                if [ "$STATUS" != "UP" ]; then
                    echo "❌ Health check failed with status: $STATUS"
                    exit 1
                else
                    echo "✅ Health check passed"
                fi